# Generated by Django 4.0.6 on 2022-07-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0006_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusOperatorProfile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("office_address", models.TextField()),
                ("ratings", models.IntegerField(default=None, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "APPROVED"),
                            ("PENDING_APPROVAL", "PENDING_APPROVAL"),
                            ("REJECTED", "REJECTED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rejection_comment", models.TextField()),
                (
                    "business_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_business_logos",
                        to="common.media",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opertor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("common.basemodel",),
        ),
    ]
