# Generated by Django 4.0.6 on 2022-07-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_basemodel_deleted_at"),
        ("bus_operator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busoperatorprofile",
            name="business_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_business_logos",
                to="common.media",
            ),
        ),
        migrations.AlterField(
            model_name="busoperatorprofile",
            name="ratings",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="busoperatorprofile",
            name="rejection_comment",
            field=models.TextField(blank=True),
        ),
    ]
