# Generated by Django 4.0.6 on 2022-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_user_created_at_user_deleted_at_user_updated_at_and_more"),
        (
            "bus_operator",
            "0002_bus_busamenities_busunavailability_busstoppage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="bus_operator.busamenities"),
        ),
        migrations.AlterField(
            model_name="bus",
            name="photos",
            field=models.ManyToManyField(blank=True, to="common.media"),
        ),
    ]
