# Generated by Django 4.0.6 on 2022-07-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_operator', '0003_alter_bus_amenities_alter_bus_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusAmenities',
            new_name='BusAmenity',
        ),
    ]
