# Generated by Django 4.0.6 on 2022-07-18 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_user_created_at_user_deleted_at_user_updated_at_and_more"),
        ("bus_operator", "0004_rename_busamenities_busamenity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="capacity",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_operator",
                to="bus_operator.busoperatorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="per_km_fare",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="busoperatorprofile",
            name="business_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="busoperatorprofile_business_logo",
                to="common.media",
            ),
        ),
        migrations.AlterField(
            model_name="busoperatorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busoperatorprofile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="busstoppage",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busstoppage_bus",
                to="bus_operator.bus",
            ),
        ),
        migrations.AlterField(
            model_name="busstoppage",
            name="distance",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="busunavailability",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busunavailability_bus",
                to="bus_operator.bus",
            ),
        ),
    ]
