# Generated by Django 4.0.6 on 2022-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_operator", "0002_alter_busoperatorprofile_business_logo_and_more"),
        (
            "bus_operator",
            "0006_alter_busstoppage_options_alter_busamenity_name_and_more",
        ),
    ]

    operations = []
