# Generated by Django 4.0.6 on 2022-07-20 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_operator', '0012_alter_busstoppage_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstoppage',
            options={'ordering': ['bus', 'count', 'journey_type'], 'verbose_name': 'Bus Stop', 'verbose_name_plural': 'Bus Stops'},
        ),
        migrations.AlterField(
            model_name='busstoppage',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
