# Generated by Django 4.0.6 on 2022-07-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_operator", "0016_busjourney"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busjourney",
            options={"ordering": ["sequence"]},
        ),
    ]
