# Generated by Django 4.0.6 on 2022-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_operator', '0020_alter_ticket_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_link',
            field=models.URLField(blank=True),
        ),
    ]
