# Generated by Django 4.0.6 on 2022-07-22 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_operator", "0022_alter_ticket_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
