version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: ./
    command: gunicorn -w 2 -b :8000 bus_ticketing.wsgi
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: "on-failure"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres.env
    # environment:
    #   - POSTGRES_USER=myinfo_user
    #   - POSTGRES_PASSWORD=testuser
    #   - POSTGRES_DB=bus_eticketing
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume: