# Generated by Django 4.0.6 on 2022-07-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_rename_is_admin_user_admin_and_more"),
    ]

    operations = []
