# Generated by Django 4.0.6 on 2022-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_user_id_user_basemodel_ptr"),
    ]

    operations = []
