# Generated by Django 4.0.6 on 2022-07-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_remove_user_basemodel_ptr_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
            bases=("common.basemodel",),
        ),
    ]
