# Generated by Django 4.0.6 on 2022-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
