
BASE_URL = "/api/v1/"

# BUS OPERATORS ENDPOINTS
OPERATORS_ENDPOINT = BASE_URL + "bus_operators"
PROFILE_ENDPOINT = OPERATORS_ENDPOINT + "profile"
OPERATOR_DETAILS_Endpoint = OPERATORS_ENDPOINT + "/{}"

# BUSES ENDPOINTS
BUSES_ENDPOINT = BASE_URL + "buses"
BUSES_SEARCH_ENDPOINT = BUSES_ENDPOINT + "/search"
BUS_STOPS_ENDPOINT = BUSES_ENDPOINT + "/{}/stops"
BUS_STOPS_DETAILS_ENDPOINT = BUSES_ENDPOINT + "/{}/stops/{}"

# TICKET ENDPOINTS
TICKETS_ENDPOINT = BASE_URL + "tickets"
TICKET_DETAILS_ENDPOINT = BASE_URL + "tickets/{}"